# Generated by Django 2.2.3 on 2019-08-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('montant_paris', models.IntegerField()),
                ('equipe', models.ForeignKey(on_delete='blank', to='Game.Equipe')),
            ],
        ),
    ]
